# Generated by Django 5.2.5 on 2025-10-15 14:07

import django.db.models.deletion
import hotel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=hotel.models.current_year, editable=False)),
                ('month', models.PositiveIntegerField(default=hotel.models.current_month, editable=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribute', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=100, unique=True)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=100, blank=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('comments', models.TextField(blank=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.partner')),
            ],
            options={
                'verbose_name': 'Partner Payment',
                'verbose_name_plural': 'Partner Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_no', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('sold', 'Sold'), ('empty', 'Empty')], default='empty', max_length=10)),
                ('sold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['shop_no'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salary', 'Salary'), ('electric', 'Electric'), ('water', 'Water'), ('registry', 'Registry'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hotel.shop')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('security', 'Security'), ('installment', 'Installment')], default='rent', max_length=20)),
                ('payment_date', models.DateField()),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.shop')),
            ],
            options={
                'verbose_name': 'Shop Payment',
                'verbose_name_plural': 'Shop Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_increment', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('rent_date', models.DateField()),
                ('year', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='hotel.shop')),
            ],
            options={
                'verbose_name': 'Shop Rent',
                'verbose_name_plural': 'Shop Rents',
                'ordering': ['-rent_date'],
            },
        ),
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('detail', models.TextField(blank=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hotel.shop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.tenant')),
            ],
            options={
                'verbose_name': 'Shop Detail',
                'verbose_name_plural': 'Shop Details',
            },
        ),
    ]
