# Generated by Django 5.2.5 on 2026-04-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.CharField(choices=[('second', 'Second Floor'), ('second-cab', 'Second Floor Cabinet'), ('third', 'Third Floor'), ('third-cab', 'Third Floor Cabinet')], default='second', max_length=10),
        ),
    ]
