# Generated by Django 5.2.5 on 2025-09-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetail',
            name='partner',
        ),
    ]
