# Generated by Django 5.2.5 on 2026-04-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_shop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
