# Generated by Django 5.2.5 on 2025-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_shopdetail_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
