# Generated by Django 5.2.5 on 2025-10-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_shop_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprent',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
