# Generated by Django 5.2.5 on 2026-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_tenant_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
