# Generated by Django 5.2.5 on 2025-10-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_shoprent_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppayment',
            name='shop_rent',
        ),
    ]
