# Generated by Django 5.2.5 on 2025-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_shoppayment_shop_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
