# Generated by Django 5.2.5 on 2025-10-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_tenant_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='amount',
            new_name='sold_amount',
        ),
    ]
