# Generated by Django 5.2.4 on 2025-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name'], 'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='partyledger',
            options={'ordering': ['transaction_date'], 'verbose_name': 'Party Ledger', 'verbose_name_plural': 'Party Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='partyprojectledger',
            options={'ordering': ['party', 'project', 'transaction_date'], 'verbose_name': 'Party Project Ledger', 'verbose_name_plural': 'Party Project Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectledger',
            options={'ordering': ['project', 'transaction_date'], 'verbose_name': 'Project Ledger', 'verbose_name_plural': 'Project Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='projectparty',
            options={'ordering': ['project', 'party'], 'verbose_name': 'Project Party', 'verbose_name_plural': 'Project Parties'},
        ),
        migrations.AlterField(
            model_name='partyprojectledger',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='partyprojectledger',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectledger',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectledger',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectparty',
            unique_together={('project', 'party')},
        ),
    ]
