# Generated by Django 5.2.5 on 2025-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_party_options_alter_partyledger_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyprojectledger',
            name='withdrawn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
